#!/usr/bin/python
from __future__ import division
import cgi
from json import dumps
# import cgitb

# cgitb.enable()

data=cgi.FieldStorage
filename=data.getfirst('filename')

with open('../saved','w') as file:
	file.write(data)